### ISSUE TITLE
Pyxel version is unavailable

### ISSUE THREAD

**Issue by deadpyxel** [humrochagf/pyxel-lander#1]
Pip is not being able to find and install version `1.2.5` of `pyxel`.

I tried using `pipx` and `pip install`, and both did not work. 
It seems pip is installing version `1.0.2`. Not sure yet how to fix it.

I am using ubuntu 18.04.3 LTS, with `python 3.6.8`.

**Comment by deadpyxel** [comment]
UPDATE: Looks like python 3.7 is needed for `pyxel==1.2.5`.

**Comment by humrochagf** [comment]
Ouch, didn't see that the newer versions of Pyxel don't support Python 3.6.

I'll change it at the docs

**Comment by humrochagf** [comment]
Done, fixed the Python version requirements to python 3.7 or higher, sorry that, and thank you for the report :)

**Comment by deadpyxel** [comment]
No worries there. Happy to help.
