### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by AnshThayil** [humrochagf/pyxel-lander#2]
I get an OSError:
`OSError: libSDL2_image-2.0.so.0: cannot open shared object file: No such file or directory` when I try to run the game.
I'm running it using python3.7 and Ubuntu 18.04

**Comment by humrochagf** [comment]
Have you installed the [Pyxel](https://github.com/kitao/pyxel) external dependencies for ubuntu?

```
sudo apt install python3 python3-pip libsdl2-dev libsdl2-image-dev
```

**Comment by AnshThayil** [comment]
My bad! Thought I had but I had done so for another system.
Good work on the game!
